#!/usr/bin/env python3
"""agent-fanout — write AGENTS.md once, generate the file every other coding agent reads.

Claude Code reads CLAUDE.md. Cursor reads .cursor/rules/*.mdc. Copilot reads
.github/copilot-instructions.md. Gemini reads GEMINI.md. They mostly want the same
content in a different place, so teams keep the same rules in five files and edit
whichever one they happen to have open. The copies drift apart from there.

This keeps one source — AGENTS.md, the convention most of these tools already
accept — and writes the rest from it.

    python3 agent_fanout.py                 # generate for detected tools
    python3 agent_fanout.py --check         # CI: exit 1 if anything is out of date
    python3 agent_fanout.py --dry-run       # show what would change
    python3 agent_fanout.py --only cursor copilot

Generated files carry a header. The tool refuses to overwrite a file without that
header, so a hand-written CLAUDE.md is never destroyed by accident.

No dependencies. Python 3.8+. MIT licensed.
Built by the team behind untactit (https://untactit.com).
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys

__version__ = "0.1.0"

SOURCE = "AGENTS.md"
MARKER = "agent-fanout:generated"

# Each target: where it goes, and how the body is wrapped.
# "mdc" wraps the body in the frontmatter Cursor expects; everything else is markdown.
TARGETS = {
    "claude":   {"path": "CLAUDE.md",                          "style": "md",
                 "label": "Claude Code"},
    "cursor":   {"path": ".cursor/rules/from-agents-md.mdc",   "style": "mdc",
                 "label": "Cursor"},
    "copilot":  {"path": ".github/copilot-instructions.md",    "style": "md",
                 "label": "GitHub Copilot"},
    "gemini":   {"path": "GEMINI.md",                          "style": "md",
                 "label": "Gemini"},
    "windsurf": {"path": ".windsurfrules",                     "style": "txt",
                 "label": "Windsurf"},
    "cline":    {"path": ".clinerules",                        "style": "txt",
                 "label": "Cline"},
    "continue": {"path": ".continuerules",                     "style": "txt",
                 "label": "Continue"},
    "zed":      {"path": ".rules",                             "style": "txt",
                 "label": "Zed"},
}

# A target is "detected" when the tool has left its own footprint in the repository.
# Generating files for tools nobody uses just adds clutter.
FOOTPRINTS = {
    "claude":   ["CLAUDE.md", ".claude"],
    "cursor":   [".cursor", ".cursorrules"],
    "copilot":  [".github/copilot-instructions.md", ".github"],
    "gemini":   ["GEMINI.md"],
    "windsurf": [".windsurfrules", ".windsurf"],
    "cline":    [".clinerules"],
    "continue": [".continuerules"],
    "zed":      [".rules", ".zed"],
}


def header(style: str, src_hash: str) -> str:
    line1 = "Generated from %s by agent-fanout. Do not edit this file." % SOURCE
    line2 = "Edit %s and re-run agent-fanout. [%s %s]" % (SOURCE, MARKER, src_hash)
    if style == "mdc":
        return "<!-- %s -->\n<!-- %s -->\n" % (line1, line2)
    if style == "txt":
        return "# %s\n# %s\n" % (line1, line2)
    return "<!-- %s -->\n<!-- %s -->\n" % (line1, line2)


def render(body: str, style: str, src_hash: str) -> str:
    head = header(style, src_hash)
    if style == "mdc":
        # Cursor's .mdc format: YAML-ish frontmatter, then the rules.
        front = ("---\n"
                 "description: Project rules, generated from %s\n"
                 "globs:\n"
                 "alwaysApply: true\n"
                 "---\n\n") % SOURCE
        return front + head + "\n" + body.rstrip() + "\n"
    return head + "\n" + body.rstrip() + "\n"


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def is_generated(text: str) -> bool:
    return MARKER in text[:4000]


def stated_hash(text: str):
    m = re.search(re.escape(MARKER) + r"\s+([0-9a-f]{12})", text[:4000])
    return m.group(1) if m else None


def detect(root: str, requested):
    if requested:
        unknown = [t for t in requested if t not in TARGETS]
        if unknown:
            raise SystemExit("unknown target(s): %s\nknown: %s"
                             % (", ".join(unknown), ", ".join(sorted(TARGETS))))
        return list(requested)
    found = []
    for name, marks in FOOTPRINTS.items():
        if any(os.path.exists(os.path.join(root, m)) for m in marks):
            found.append(name)
    return found


def plan(root, targets, body, src_hash):
    """Decide what to do with each target without touching disk."""
    actions = []
    for name in targets:
        spec = TARGETS[name]
        path = os.path.join(root, spec["path"])
        wanted = render(body, spec["style"], src_hash)
        if not os.path.exists(path):
            actions.append((name, path, "create", wanted))
            continue
        try:
            with open(path, "r", encoding="utf-8") as fh:
                current = fh.read()
        except OSError as exc:
            actions.append((name, path, "unreadable: %s" % exc, None))
            continue
        if not is_generated(current):
            # 내용을 함께 싣는다 — --force 가 이걸 쓴다.
            actions.append((name, path, "skip-handwritten", wanted))
        elif current == wanted:
            actions.append((name, path, "current", None))
        else:
            actions.append((name, path, "update", wanted))
    return actions


def apply(actions, force=False):
    """Write the planned files. Returns the outcome per target, since --force
    changes what actually happened and the caller has to report the truth."""
    outcome = []
    for name, path, action, content in actions:
        eff = action
        if action == "skip-handwritten" and force:
            eff = "overwrite"
        if eff in ("create", "update", "overwrite") and content is not None:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
        outcome.append((name, path, eff))
    return outcome


def rel(path, root):
    try:
        return os.path.relpath(path, root)
    except ValueError:
        return path


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="agent-fanout",
        description="Write AGENTS.md once, generate what every other coding agent reads.")
    ap.add_argument("root", nargs="?", default=".", help="project root (default: .)")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated file is missing or out of date")
    ap.add_argument("--dry-run", action="store_true", help="show changes, write nothing")
    ap.add_argument("--only", nargs="+", metavar="TOOL",
                    help="generate only these targets (default: auto-detect)")
    ap.add_argument("--all", action="store_true", help="generate for every known target")
    ap.add_argument("--force", action="store_true",
                    help="overwrite hand-written files (they are skipped by default)")
    ap.add_argument("--list", action="store_true", help="list known targets and exit")
    ap.add_argument("--version", action="version", version="agent-fanout %s" % __version__)
    args = ap.parse_args(argv)

    if args.list:
        for k in sorted(TARGETS):
            print("%-9s %-38s %s" % (k, TARGETS[k]["path"], TARGETS[k]["label"]))
        return 0

    root = os.path.abspath(args.root)
    src = os.path.join(root, SOURCE)
    if not os.path.exists(src):
        print("No %s in %s" % (SOURCE, root), file=sys.stderr)
        print("Create one, or point at a project that has it.", file=sys.stderr)
        return 2

    with open(src, "r", encoding="utf-8") as fh:
        body = fh.read()
    if not body.strip():
        print("%s is empty; nothing to fan out." % SOURCE, file=sys.stderr)
        return 2
    src_hash = digest(body)

    targets = sorted(TARGETS) if args.all else detect(root, args.only)
    if not targets:
        print("No coding agents detected in %s." % rel(root, os.getcwd()))
        print("Use --only TOOL, or --all. Run --list to see the names.")
        return 0

    actions = plan(root, targets, body, src_hash)

    stale = [a for a in actions if a[2] in ("create", "update")]
    hand = [a for a in actions if a[2] == "skip-handwritten"]
    ok = [a for a in actions if a[2] == "current"]

    if args.check:
        for name, path, action, _ in stale:
            print("out of date: %s (%s)" % (rel(path, root), name))
        for name, path, _, _ in hand:
            print("hand-written, not managed: %s (%s)" % (rel(path, root), name))
        if not stale:
            print("All %d generated file(s) match %s." % (len(ok), SOURCE))
        return 1 if stale else 0

    if args.dry_run:
        for name, path, action, _ in actions:
            print("%-18s %s" % (action, rel(path, root)))
        return 0

    outcome = apply(actions, force=args.force)
    written = 0
    for name, path, eff in outcome:
        if eff in ("create", "update", "overwrite"):
            written += 1
            print("%-9s %s" % (eff, rel(path, root)))
        elif eff == "skip-handwritten":
            print("%-9s %s  (not generated by this tool; use --force to replace)"
                  % ("skip", rel(path, root)))
        elif eff.startswith("unreadable"):
            print("%-9s %s  (%s)" % ("error", rel(path, root), eff))
    if written == 0 and not any(e[2] == "skip-handwritten" for e in outcome):
        print("Everything already matches %s." % SOURCE)
    return 0


if __name__ == "__main__":
    sys.exit(main())

